name: Deploy next app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      ENV_FILE: ${{ vars.ENV_FILE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install --force



      - name: Build Next app
        run: npm run build

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clean remote folder
        run: |
          ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$SSH_HOST << EOF
            sudo rm -rf /var/www/website/*
            mkdir -p /var/www/website
            exit
          EOF

      - name: Upload files to server
        run: |
          scp -P $SSH_PORT -r .next public package.json next.config.mjs $SSH_USERNAME@$SSH_HOST:/var/www/website/

      - name: Restart app on server
  run: |
    ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$SSH_HOST << 'EOF'
      cd /var/www/website

      # Write .env.production file using GitHub Actions variable
      echo "$ENV_FILE" > .env.production

      # Reinstall prod dependencies (if needed)
      npm install --production

      # Restart app with pm2
      pm2 restart knot-web || pm2 start 'npx next start -p 4000' --name knot-web
      exit
    EOF

